from __future__ import annotations

import json
from typing import Any, Callable

import httpx

from mcp_client import McpClient


def create_design_tool_node(
    mcp_client: McpClient,
    allowed_tools: list[dict[str, Any]],
    dbg: Callable[[str], None],
) -> Callable[[dict[str, Any]], dict[str, Any]]:
    """
    Create a tool execution node for design operations.
    Handles all tool calls across different design actions.
    """

    allowed_tool_names = {str(tool.get("name")) for tool in allowed_tools if tool.get("name")}
    tool_aliases = {
        "compute_site_area": "area_of_the_compute_site",
        "calculateSiteArea": "area_of_the_compute_site",
        "siteBoundary": "site_boundary",
        "siteBoundaryReader": "site_boundary_reader_04",
    }

    def design_tool_node(state: dict[str, Any], /) -> dict[str, Any]:
        dbg("[workflow][tool] Enter node")

        pending_tools = state.get("pending_tool_calls", [])
        if not pending_tools:
            dbg("[workflow][tool] No pending tools")
            state["pending_action"] = "final"
            state["final_response"] = "No valid tools were generated by the model."
            return state

        tool_results: list[str] = []

        for pending_tool in pending_tools:
            state["tool_execution_count"] += 1
            
            if state["tool_execution_count"] > state.get("max_iterations", 10):
                raise RuntimeError("Max tool executions exceeded")

            tool_name = pending_tool.get("name", pending_tool.get("tool_name"))
            if not tool_name:
                raise RuntimeError("Tool call missing name")

            if tool_name in tool_aliases:
                tool_name = tool_aliases[tool_name]

            if tool_name not in allowed_tool_names:
                dbg(f"[workflow][tool] Skipping unsupported tool: {tool_name}")
                continue

            tool_arguments = pending_tool.get("arguments", {})
            if not isinstance(tool_arguments, dict):
                raise RuntimeError("Tool arguments must be an object")

            # Filter out None values
            filtered_args = {
                key: value for key, value in tool_arguments.items() if value is not None
            }

            dbg(
                f"[workflow][tool] Executing | name={tool_name} | "
                f"args={filtered_args} | count={state['tool_execution_count']}"
            )

            try:
                tool_output = mcp_client.call_tool(tool_name, filtered_args)
            except httpx.ReadTimeout:
                timeout_seconds = getattr(mcp_client, "_timeout_seconds", None)
                timeout_text = (
                    f"{timeout_seconds:.0f}s" if isinstance(timeout_seconds, (int, float)) else "the configured timeout"
                )
                tool_output = f"Tool '{tool_name}' timed out after {timeout_text}."
                state["pending_action"] = "final"
                state["final_response"] = tool_output

            dbg(f"[workflow][tool] Result: {tool_output[:100]}...")
            
            tool_results.append(tool_output)
            state["last_tool_result"] = tool_output
            state["design_state"]["last_tool_result"] = tool_output

        state["pending_tool_calls"] = []
        state["tool_results"] = tool_results
        
        return state

    return design_tool_node
